### ISSUE TITLE
i am getting these errors after clicking deploy , i have copied code from index.js and pack.js

### ISSUE THREAD

**Issue by sachinnelwade** [actions-on-google/dialogflow-name-psychic-nodejs#11]
The deployment of your Cloud Function failed:
Function load error: Code in file index.js can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module './util'
at Function.Module._resolveFilename (module.js:476:15)
at Function.Module._load (module.js:424:25)
at Module.require (module.js:504:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/user_code/index.js:25:16)
at Module._compile (module.js:577:32)
at Object.Module._extensions..js (module.js:586:10)
at Module.load (module.js:494:32)
at tryModuleLoad (module.js:453:12)
at Function.Module._load (module.js:445:3)

**Comment by taycaldwell** [comment]
The code in `index.js` depends on code from the file `util.js`. If you are copying the code directly, you will also need to copy `util.js` and put it in the same directory as `index.js`.

I would recommend checking out the sample code via `git clone` and deploying it rather than copying each individual file.
